name: "Legal500 US"
required_fields:
  - "A_preliminary_information.A1_firm_name"
  - "A_preliminary_information.A2_practice_area"
  - "A_preliminary_information.A3_location_jurisdiction"
  - "B_department_information.B1_department_name"
  - "B_department_information.B10_department_best_known_for"
  - "C_feedback"
  - "D_publishable_information.publishable_matters"
  - "E_confidential_information"
fields:
  A_preliminary_information:
    description: "Firm Name, Country, Practice Area, and Contact details."
    state_mapping: "submission.A_preliminary_information"
  B_department_information:
    description: "Department Name, Diversity, Lawyers Ranked, etc."
    state_mapping: "submission.B_department_information"
  C_feedback:
    description: "Feedback and comments on barristers and other firms."
    state_mapping: "submission.C_feedback"
  D_publishable_information:
    description: "Publishable clients and matters."
    state_mapping: "submission.D_publishable_information"
  E_confidential_information:
    description: "Confidential clients and matters."
    state_mapping: "submission.E_confidential_information"
